version: "3.8"


services:
  mywebapp_ci:
    build: .
    container_name: mywebapp_ci_container
    ports:
      - "8081:80"
    volumes:
      - ./code:/usr/share/nginx/html
    restart: always

volumes:
  web_data:
  
